services:
  web:
    build: .
    restart: always
    command: /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # NOTE: Untested with multiple GPUs
              # count: 1 # GPU count | Default setting is to use all GPUs
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./tirtha  # On Host machine
        target: /var/www/tirtha  # Inside docker container
    env_file:
      - ./docker.env
    ports:
      - "8000:8000"
      - "15672:15672"
    depends_on:
      - db

  db:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=docker  # NOTE: This is only here to avoid runtime error. Use docker.env to provide the password.
    env_file:
      - ./docker.env
    ports:
      - "8001:5432"  # Host:Container
